### ISSUE TITLE
new economyvariants buggy because of same item?

### ISSUE THREAD

**Issue by CloudeLecaw** [LMBishop/MoneyPouch#10]
i designted a test item

```
    karottenkiste-1:
      name: "&6&lEine echte Karottenkiste &r&7(Rechtsklick)"
      item: "CHEST"
      pricerange:
        from: 2
        to: 5
      options:
        economytype: "karottenkiste.yml"
        permission-required: true      # requires permission "moneypouch.pouches.karottenkiste-1"
      lore:
        - "&7Öffne diese Kiste, um Karotten zu erhalten!"
```
```
economy:
  xp:
    prefix: ""
    suffix: " XP"
  vault:
    prefix: "$"
    suffix: ""
  lemonmobcoins:
    prefix: ""
    suffix: " Mobmünzen"
  karottenkiste.yml:
    prefix: ""
    suffix: " Möhren"

```

the custom file i called karottenkiste,yml and putted it into the new custom ecoomy folder..
![Snag_a56237f](https://user-images.githubusercontent.com/12080017/104806840-b10f7780-57da-11eb-9fc8-65edaa29d612.png)
```
# This is an example of a custom economy
# The expected behaviour is for this to be a pouch containing diamonds, rather than money,
# however you can use this feature to make this plugin compatible with any economy plugin,
# as long as there is a command to give money.
#
# The name of this file is the id of the economy, and must be alphanumeric with no spaces and unique
# The command below will be executed when a player opens a pouch of this economy, replace %player% with the player
# and %amount% with the amount
transaction-prize-command: "cmi give %player% carrot %prize%"

# You can configure the prefixes/suffixes the normal way in the main config

```
_little side issue:
(in the example yml it sais %amount% in the command %prize% ...
so one seems to be wrong here)_

--------------------------------------------------------------
server was reststarted

now instead of getting some carrots i got money,, like the Moneybox - that has a normal chest as item too....

So i Asume this  is a bug.. or the whole new feature does not work...? 

![Snag_a4de2a5](https://user-images.githubusercontent.com/12080017/104806654-6c371100-57d9-11eb-841a-014fbbc61d2c.png)

![Snag_a4f9045](https://user-images.githubusercontent.com/12080017/104806682-aa343500-57d9-11eb-8c20-4ee5ccdd2d0b.png)

![Snag_a4ff96f](https://user-images.githubusercontent.com/12080017/104806687-ba4c1480-57d9-11eb-9fa9-e9424451be12.png)
