### ISSUE TITLE
wrong economytype? what i do wrong?

### ISSUE THREAD

**Issue by CloudeLecaw** [LMBishop/MoneyPouch#11]
![Snag_181c12c](https://user-images.githubusercontent.com/12080017/104849594-cbd11180-58ea-11eb-937f-6c8c41a8944d.png)

```
    karottenkiste-1:
      name: "&6&lEine echte Karottenkiste &r&7(Rechtsklick)"
      item: "CHEST"
      pricerange:
        from: 2
        to: 5
      options:
        economytype: "karottenkiste-1"
        permission-required: true      # requires permission "moneypouch.pouches.karottenkiste-1"
      lore:
        - "&7Öffne diese Kiste, um Karotten zu erhalten!"
```
```
# Economy prefixes and suffixes
economy:
  xp:
    prefix: ""
    suffix: " XP"
  vault:
    prefix: "$"
    suffix: ""
  lemonmobcoins:
    prefix: ""
    suffix: " Mobmünzen"
  karottenkiste-1:
    prefix: ""
    suffix: " Möhren"
```

![Snag_18443ff](https://user-images.githubusercontent.com/12080017/104849648-2e2a1200-58eb-11eb-933d-4d1fafa2fe8e.png)

So what have i dont wrong here?
