### ISSUE TITLE
Custom Player Head Not Working

### ISSUE THREAD

**Issue by BlackBeltPanda** [LMBishop/MoneyPouch#18]
Running MoneyPouch v3.6.1 on Purpur v1.17.1

After specifying the "owner-base64" value in the config with an Item Type "PLAYER_HEAD", the plugin only gives an unskinned player head. This is what the config section looks like:
```
pouches:
  tier:
    # Define pouches here
    commonMoney:
      name: "&6&lCommon Money Pouch &r&7(Right Click)"
      item: "PLAYER_HEAD"
      owner-base64: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM0MzQ4ZDMzOWE3YmRiYjRkYzNlYTM5YzM0NDQ3Y2E3NjM4NDZiMjllMDZmNTY4ZTBjOGM1MjE5MjAzZGY5ZiJ9fX0="
      pricerange:
        from: 1000
        to: 5000
      options:
        economytype: "VAULT"
      lore:
        - "&7Open this pouch to receive money!"
```
