### ISSUE TITLE
Perm Issue

### ISSUE THREAD

**Issue by MayDayRains** [LMBishop/MoneyPouch#27]
Heyo! First of all great plugin!

So we have a moneypouch that is not working. It says you do not have the permission to use it but permission is set to false. There are no errors in console. So I am just a bit lost. Here is the pouch we are having issues with: 

```
    T1:
      name: "&x&D&2&B&4&8&C&lT&x&D&2&B&4&8&C&li&x&D&2&B&4&8&C&le&x&D&2&B&4&8&C&lr&x&D&2&B&4&8&C&l &x&D&2&B&4&8&C&lI &fMoney Pouch"
      item: "BOOK"
      pricerange:
        from: 1000
        to: 5000
      options:
          economytype: "VAULT"
          permission-required: false
      lore:
          - "&7"
          - "&8$1,000 &7- &8$5,000"
          - "&7"
          - "&7Right click this pouch to"
          - "&7see what amount is inside!"
      custommodeldata: 10009
```

Also I have tried removing it and adding it back in - that also did not work.
