### ISSUE TITLE
prefix

### ISSUE THREAD

**Issue by dotxzxc** [LMBishop/MoneyPouch#4]
cannot change the economy prefix

**Comment by dotxzxc** [comment]
tried to change the ITEM it gives me STONE

**Comment by LMBishop** [comment]
well what have you tried?

**Comment by dotxzxc** [comment]
item: paper
item: experience_bottle

**Comment by LMBishop** [comment]
i can't replicate the bug, ensure your config follows the following format
```
economy:
  xp:
    prefix: ""
    suffix: " XP"
  vault:
    prefix: "$"
    suffix: ""
  lemonmobcoins:
    prefix: ""
    suffix: " Mob Coins"
```

as for the item bug, a fix will be pushed soon
