### ISSUE TITLE
Bug in translation (in chat when shop is disabled)

### ISSUE THREAD

**Issue by CloudeLecaw** [LMBishop/MoneyPouch#6]
```
# Messages here
messages:
  no-perm: "&6Du kannst diesen Paket in dieser Welt nicht benutzen."
  full-inv: "&c%player%'s Inventar ist voll!"
  give-item: "&e%player% wurde eine %item%&6 gegeben."
  receive-item: "&6Du hast eine %item% &6erhalten."
  prize-message: "&6Du erhälst &c%prize%%prefix%%suffix%&6!"
  aready-opening: "&cBitte warten Sie, bis die aktuelle Kistenöffnung abgeschlossen ist!"
  inventory-full: "&cDein Inventar ist voll."
  purchase-success: "&6Du hast %item%&6 für &c%prefix%%price%%suffix%&6 erhalten."
  purchase-fail: "&cDu hast nicht &c%prefix%%price%%suffix%&6."
  shop-disabled: "&cDer Paketeladen ist deaktiviert."
```

![Snag_2bcd40c](https://user-images.githubusercontent.com/12080017/104236481-e9b7f580-5456-11eb-9794-897c78fa1823.png)

Ingame you still see the english line.
so its missing or taking the line from wrong place...
